
export const myProjects = [
  {
    projectTitle: "Coin Crafter",
    category: ["react"],
    tags: ["React", "Material-ui", "Firebase"],
    details: "",
    imgPath: "./images/p-coin.png",
    link:"https://coin-crafter.netlify.app/",
    gLink: "https://github.com/mdrony5134/Crypto-Coin-Crafter",
  },
  {
    projectTitle: "Redstore-Ecommerce",
    category: ["css"],
    tags: ["Html", "css"],
    details: "",
    imgPath: "./images/p2.png",
    link:"https://mdrony5134.github.io/RedStore-Ecommerce-Website/",
    gLink: "https://github.com/mdrony5134/RedStore-Ecommerce-Website",
  },
  {
    projectTitle: "Responsive Startup Website",
    category: ["css"],
    tags: ["Html", "css", "javascript"],
    details: "",
    imgPath: "./images/p-startup.png",
    link:" https://mdrony5134.github.io/Responsive-Startup-Website/",
    gLink: "https://github.com/mdrony5134/Responsive-Startup-Website",
  },
  {
    projectTitle: "Appwrite Blog",
    category: ["react"],
    tags: ["React ", "Tailwind ", "Appwrite "],
    details: "",
    imgPath: "./images/p6-r.png",
    link: "appwrite-blog-site.vercel.app",
    gLink: "https://github.com/mdrony5134/appwrite-blog",
  },
  {
    projectTitle: "Tic-Tac-To Game",
    category: ["js"],
    tags: ["Html", "css", "JavaScript"],
    imgPath: "./images/p4-j.png",
    link:"https://mdrony5134.github.io/tic-tac-toe/",
    gLink:"https://github.com/mdrony5134/tic-tac-toe",
  },
//   {
//     projectTitle: "node project",
//     category: ["node"],
//     imgPath: "./images/7.jpg",
//   },
//   {
//     projectTitle: "node project",
//     category: ["node"],
//     imgPath: "./images/8.jpg",
//   },
  {
    projectTitle: "Image Search Site",
    category: ["js"],
    tags: ["Html", "css", "JavaScript"],
    details: "",
    imgPath: "./images/p3-j.png",
    link:" https://mdrony5134.github.io/image-search-app/",
    gLink:"https://github.com/mdrony5134/image-search-app",
  },
];
